import{i as a,S as u}from"./assets/vendor-5b791d57.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();const d=document.querySelector(".input-search"),f=document.getElementById("search-form"),l=document.getElementById("gallery");f.addEventListener("submit",function(s){s.preventDefault();const o=d.value.trim();o?(h(),fetch(`https://pixabay.com/api/?key=29942317-e3405ade5aa33d4d063a2fbeb&q=${o}&image_type=photo&orientation=horizontal&safesearch=true`).then(t=>{if(!t.ok)throw new Error(t.status);return t.json()}).then(t=>{c(),t.hits.length>0?m(t.hits):a.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"})}).catch(t=>{c(),console.log(t)})):a.error({title:"Error",message:"Please enter a search keyword."})});function h(){l.innerHTML="<p>Loading images, please wait...</p>"}function c(){l.innerHTML=""}function m(s){const o=[],t=s.map(e=>(o.push({src:e.largeImageURL,title:`Likes: ${e.likes}, Views: ${e.views}, Comments: ${e.comments}, Downloads: ${e.downloads}`}),`<a href="${e.largeImageURL}" data-lightbox="gallery" data-title="${e.tags}">
              <img src="${e.webformatURL}" alt="${e.tags}">
              <ul>
              <li>Likes:<br /> ${e.likes}</li>
              <li>Views:<br /> ${e.views}</li>
              <li>Comments:<br /> ${e.comments}</li>
              <li>Downloads:<br /> ${e.downloads}</li>
              </ul>
            </a>`)).join("");l.innerHTML=`${t}`,new u('a[data-lightbox="gallery"]').refresh()}
//# sourceMappingURL=commonHelpers.js.map
